ChillApp/Models/Entites/Task.cs
using System;

namespace ChillApp.Models.Entites
{
    public class Task
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Descirption { get; set; }
        public DateTime CreatedDate { get; set; }
        public bool IsDeleted { get; set; }

        public int StatusId { get; set; }
        public virtual Status Status { get; set; }
        
        public int UserId { get; set; }
        public virtual User User { get; set; }      

        
    }
}

ChillApp/Controllers/TaskController.cs
using System;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using ChillApp.Models.Context;
using ChillApp.Models.Dto;
using ChillApp.Models.Entites;

namespace ChillApp.Controllers
{
    public class TaskController : Controller
    {
        private DatabaseContext db = new DatabaseContext();
        public ActionResult Index()
        {
            var userLogin = Session["userLogin"] as User;
            TaskStatusModel taskStatusModel = new TaskStatusModel
            {
                Status = db.Status.Where(x=>x.StatusTypeId==2).ToList(),
                Task = db.Task.Where(x=>x.User.Id==userLogin.Id && x.IsDeleted==false).ToList()
            };
            return View(taskStatusModel);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Task model)
        {
            if (!string.IsNullOrEmpty(model.Title) && !string.IsNullOrEmpty(model.Descirption))
            {
                var userLogin = Session["userLogin"] as User;
                model.CreatedDate=DateTime.Now;
                model.UserId = userLogin.Id;
                model.StatusId = 3;
                db.Task.Add(model);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }
        public ActionResult Edit(int? id)
        {
            if (id!=null)
            {
                Task result = db.Task.FirstOrDefault(x => x.Id == id);
                if (result==null)
                {
                    return HttpNotFound();
                }
                ViewBag.StatusId = new SelectList(db.Status.Where(x=>x.StatusTypeId==2).ToList(), "Id", "Name",result.StatusId);
                return View(result);
            }
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }
        [HttpPost]
        public ActionResult Edit(Task model)
        {
            if (!string.IsNullOrEmpty(model.Title) && !string.IsNullOrEmpty(model.Descirption))
            {
                Task result = db.Task.FirstOrDefault(x => x.Id == model.Id);
                result.Title = model.Title;
                result.Descirption = model.Descirption;
                result.StatusId = model.StatusId;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.StatusId = new SelectList(db.Status.Where(x=>x.StatusTypeId==2).ToList(), "Id", "Name",model.StatusId);
            return View(model);
        }
        public ActionResult NextStep(int? id)
        {
            if (id!=null)
            {
                Task result = db.Task.FirstOrDefault(x => x.Id == id);
                if (result!=null)
                {
                    switch (result.StatusId)
                    {
                        case 3 : 
                            result.StatusId = 4;
                            break;
                        case 4 :
                            result.StatusId = 5; 
                            break;
                        case 5 :
                            result.IsDeleted = true;
                            break;
                    }

                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return HttpNotFound();
            }
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }
        // TODO delete actionu json olacak, bir page olmayacak. Swift Alert Kullanilabilir.
        public ActionResult Delete()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Delete(Task model)
        {
            return View();
        }
    }
}

ChillApp/Views/Task/Create.cshtml
@{
    ViewBag.Title = "New Task";
}

<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item">
                        <a href="/">Dasboard</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="/task">Task</a>
                    </li>
                    <li class="breadcrumb-item active">New Task</li>
                </ol>
            </div>
            <h4 class="page-title">New Task</h4>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-xl-12">
                        @using (Html.BeginForm("Create", "Task", FormMethod.Post))
                        {
                            <div class="form-group">
                                <label for="">Title</label>
                                <input type="text" id="Title" name="Title" class="form-control" placeholder="Enter Task Title">
                            </div>

                            <div class="form-group">
                                <label for="">Overview</label>
                                <textarea class="form-control" id="Descirption" name="Descirption" rows="5" placeholder="Enter Task Descirption"></textarea>
                            </div>
                            <div class="text-right">
                                <div class="btn-group mb-2 ml-2">
                                    <button type="sumbit" class="btn btn-primary btn-sm">Create</button>
                                </div>
                            </div>
                        }

                        @* <div class="form-group mb-0"> *@
                        @*     <label for="@Model.Status">Status</label> *@
                        @*     <select class="form-control select2" data-toggle="select2"> *@
                        @*         <option>Select</option> *@
                        @*         <option value="AZ">Mary Scott</option> *@
                        @*         <option value="CO">Holly Campbell</option> *@
                        @*         <option value="ID">Beatrice Mills</option> *@
                        @*         <option value="MT">Melinda Gills</option> *@
                        @*         <option value="NE">Linda Garza</option> *@
                        @*         <option value="NM">Randy Ortez</option> *@
                        @*         <option value="ND">Lorene Block</option> *@
                        @*         <option value="UT">Mike Baker</option> *@
                        @*     </select> *@
                        @* </div> *@
                    </div> <!-- end col-->
                </div>
            </div> <!-- end card-body -->
        </div> <!-- end card-->
    </div> <!-- end col-->
</div>
<!-- end row-->

ChillApp/Views/Task/Delete.cshtml
@model dynamic

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>title</h2>

ChillApp/Views/Task/Edit.cshtml
@model ChillApp.Models.Entites.Task

@{
    ViewBag.Title = "title";
}

<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item">
                        <a href="/">Dasboard</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="/task">Task</a>
                    </li>
                    <li class="breadcrumb-item active">Task Edit</li>
                </ol>
            </div>
            <h4 class="page-title">Task Edit</h4>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-xl-12">
                        @using (Html.BeginForm("Edit", "Task", FormMethod.Post))
                        {
                            <div class="form-group">
                                <label for="">Title</label>
                                <input type="text" id="Title" name="Title" value="@Model.Title" class="form-control" placeholder="Enter Task Title">
                            </div>

                            <div class="form-group">
                                <label for="">Overview</label>
                                <textarea class="form-control" id="Descirption" name="Descirption" rows="5" placeholder="Enter Task Descirption">@Model.Descirption</textarea>
                            </div>

                            <div class="form-group"> 
                                <label for="@Model.Status">Status</label>
                                @Html.DropDownList("StatusId", null, htmlAttributes: new {@class = "form-control"})
                            </div>
                            
                            <div class="text-right">
                                <div class="btn-group mb-2 ml-2">
                                    <button type="sumbit" class="btn btn-warning btn-sm">Edit</button>
                                </div>
                            </div>
                        }

                      
                    </div> <!-- end col-->
                </div>
            </div> <!-- end card-body -->
        </div> <!-- end card-->
    </div> <!-- end col-->
</div>

ChillApp/Views/Task/Index.cshtml
@model ChillApp.Models.Dto.TaskStatusModel
@{
    ViewBag.Title = "Task List";
}

<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <h4 class="page-title">Task List</h4>
        </div>
    </div>
</div>

<div class="row">
<div class="col-12">
<div class="board">

@foreach (var status in Model.Status)
{
    <div class="tasks">
    <h5 class="mt-0 task-header">@status.Name (@Model.Task.Count(x => x.StatusId==status.Id))</h5>
    <div id="task-list-one" class="task-list-items">

       @foreach (var task in Model.Task.Where(x => x.StatusId == status.Id))
       {
            <div class="card mb-0">
            <div class="card-body p-3">
                <small class="float-right text-muted">@task.CreatedDate.ToString("dd MMMM, yyyy")</small>
                @* TODO status tablosundaki renge olucak ve task tablosuna tag diye prop eklenecek*@
                @* <span class="badge badge-danger">High</span> *@

                <h5 class="mt-2 mb-2">
                    <a href="#" data-toggle="modal" data-target="#task-detail-modal" class="text-body">@task.Title</a>
                </h5>


                <div class="dropdown float-right">
                    <a href="#" class="dropdown-toggle text-muted arrow-none" data-toggle="dropdown" aria-expanded="false">
                        <i class="mdi mdi-dots-vertical font-18"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right">
                        <a href="/task-edit/@task.Id" class="dropdown-item"><i class="mdi mdi-pencil mr-1"></i>Edit</a>
                        <a href="/task-delete/@task.Id" class="dropdown-item"><i class="mdi mdi-delete mr-1"></i>Delete</a>
                        <a href="/next-step/@task.Id" class="dropdown-item"><i class="mdi mdi-exit-to-app mr-1"></i>Next Step</a>
                    </div>
                </div>
                <p class="mb-0">
                    <span class="align-middle">@task.User.Fullname</span>
                </p>
            </div> <!-- end card-body -->
        </div>
       }
        

    </div> <!-- end company-list-1-->
</div>
}


</div> <!-- end .board-->
</div> <!-- end col -->
</div>